weights: yolov5s.pt
cfg: models/yolov5s_kaist-rgbt.yaml
data: data/kaist-rgbt.yaml
hyp:
  lr0: 0.005
  lrf: 0.005
  momentum: 0.937
  weight_decay: 0.0005
  warmup_epochs: 2.0
  warmup_momentum: 0.8
  warmup_bias_lr: 0.05
  box: 0.05
  cls: 0.3
  obj: 0.7
  fl_gamma: 0.0
  cls_pw: 1.0
  obj_pw: 1.0
  iou_type: WIoU
  wiou_beta: 2.0
  iou_t: 0.2
  anchor_t: 4.0
  degrees: 0.0
  translate: 0.01
  scale: 0.05
  shear: 0.0
  perspective: 0.0
  mosaic: 0.1
  mixup: 0.05
  copy_paste: 0.0
  hsv_h: 0.0005
  hsv_s: 0.05
  hsv_v: 0.02
  flipud: 0.0
  fliplr: 0.5
epochs: 100
batch_size: 16
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
evolve_population: data\hyps
resume_evolve: null
bucket: ''
cache: null
device: '0'
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 16
project: train
name: yolov5s-rgbt
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
save_period: -1
seed: 0
local_rank: -1
rgbt: true
entity: chomk0216-hanyang-university
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: train\yolov5s-rgbt2
